my_file = open('file_2.txt', 'r', encoding='utf-8')
content = my_file.read()
print(f'Содержимое файла: \n{content}')
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_file.close()
my_file = open('file_2.txt', 'r', encoding='utf-8')
content = my_file.readlines()
print(f'Количество строк в файле - {len(content)}')
my_file.close()
